
---
name: CI
on:
  pull_request:
  push:
jobs:
  melpazoid:
    runs-on: ubuntu-latest
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: 28.2
    - uses: actions/checkout@v3
    - name: Set up uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
    - name: Install
      run: |
        uv python install 3.10
        git clone https://github.com/riscy/melpazoid.git ~/melpazoid
        uv venv ~/melpazoid/.venv --python 3.10
        . ~/melpazoid/.venv/bin/activate
        uv pip install ~/melpazoid
    - name: Run
      env:
        LOCAL_REPO: ${{ github.workspace }}
        RECIPE: (noir-ts-mode :fetcher github :repo "hhamud/noir-ts-mode")
      run: |
        . ~/melpazoid/.venv/bin/activate
        echo "$GITHUB_REF"
        make -C ~/melpazoid
